### ISSUE TITLE
test_python_error_to_native_58 fails due to unexpected empty output from irule

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_python#150]
When running plugin version 4.3.0.1 in server built from tip of main, `test_python_error_to_native_58` fails.
The same failure occurs in my PR #140, so presumably this has not been fixed yet.

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/f71eb61912320be2ae5c74e0905d04f9).

```
 --- IrodsSession: icommand executed by [alice#tempZone] [irule -r irods_rule_engine_plugin-irods_rule_language-instance writeLine("stdout", error("SYS_INVALID_FILE_PATH") == errorcode(myrule())) null ruleExecOut] --- 
Assert Command: irule -r irods_rule_engine_plugin-irods_rule_language-instance writeLine("stdout", error("SYS_INVALID_FILE_PATH") == errorcode(myrule())) null ruleExecOut
Expecting STDOUT_SINGLELINE: ['true']
  stdout:
    | 
  stderr:
    | 
Output not found

FAILED TESTING ASSERTION


======================================================================
FAIL: test_python_error_to_native_58 (irods.test.test_python_rule_engine_plugin.Test_Python_Rule_Engine_Plugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_python_rule_engine_plugin.py", line 106, in test_python_error_to_native_58
    self.user0.assert_icommand(
  File "/var/lib/irods/scripts/irods/test/session.py", line 164, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
```

**Comment by alanking** [comment]
I believe this is fixed by changes made in #171. We observed this test failure in the run up to 4.3.1.0 and the tests are now passing.
