### ISSUE TITLE
test_remote_native_rule_engine_plugin_instance_6465 fails in lib.delayAssert

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_python#151]
When running plugin version 4.3.0.1 in server built from tip of main, `test_remote_native_rule_engine_plugin_instance_6465` fails.
The same failure occurs in my PR #140, so presumably this has not been fixed yet.

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/eb574be5134eff18214b56e26cce138b).

```
 --- IrodsSession: icommand executed by [otherrods#tempZone] [irule -r irods_rule_engine_plugin-irods_rule_language-instance -F /tmp/tmpu77es_pl.r] --- 
Assert Command: irule -r irods_rule_engine_plugin-irods_rule_language-instance -F /tmp/tmpu77es_pl.r
Expecting EMPTY: ['']
  stdout:
    | 
  stderr:
    | 
Output found


======================================================================
FAIL: test_remote_native_rule_engine_plugin_instance_6465 (irods.test.test_rule_engine_plugin_framework.Test_Rule_Engine_Plugin_Framework)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_rule_engine_plugin_framework.py", line 112, in test_remote_native_rule_engine_plugin_instance_6465
    lib.delayAssert(
  File "/var/lib/irods/scripts/irods/lib.py", line 565, in delayAssert
    raise AssertionError
AssertionError
```

**Comment by SwooshyCueb** [comment]
Despite the name of this test, it is only run when the PREP is installed and configured.
