### ISSUE TITLE
test_with_modified_rulebase_off_boundary fails in modify_rulebase_and_tst

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_rule_engine_plugin_python#152]
When running plugin version 4.3.0.1 in server built from tip of main, `test_with_modified_rulebase_off_boundary` fails.
This failure occurs as a non-`AssertionError` exception being raised during the test, which results in the failure being logged as an error in the test.
The same failure occurs in my PR #140, so presumably this has not been fixed yet.

The test is running in an Ubuntu 20.04 container, using postgres.

Here's some of the test output. I've put a more complete log [here](https://gist.github.com/SwooshyCueb/da099cf0284503b07910af3d3452f1e8).

```
======================================================================
ERROR: test_with_modified_rulebase_off_boundary (irods.test.test_prep_genquery_iterator.Test_Genquery_Iterator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_prep_genquery_iterator.py", line 648, in test_with_modified_rulebase_off_boundary
    self.boundary_with_size(512 + 7 * 8 * 9, self.modify_rulebase_and_tst, pre_start = True)
  File "/var/lib/irods/scripts/irods/test/test_prep_genquery_iterator.py", line 680, in boundary_with_size
    func(N)
  File "/var/lib/irods/scripts/irods/test/test_prep_genquery_iterator.py", line 810, in modify_rulebase_and_tst
    self.assertNotEqual( out_tuple[0][0], out_tuple[1][0]) # keys not a match ("actual" != "predicted")
IndexError: list index out of range
```

**Comment by alanking** [comment]
I believe this is fixed by changes made in #171. We observed this test failure in the run up to 4.3.1.0 and the tests are now passing.
