### ISSUE TITLE
callback object exists for delayExec() but not remoteExec()

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_rule_engine_plugin_python#9]
On a machine with hostname  **daniel-ThinkPad-W540** , we are observing two scenarios in the use of the python rule engine plugin during calls to delayExec() and remoteExec() .  Scenario (1) acts as expected, whereas scenario (2) displays the problem behavior.
Note incidentally that in each scenario, the remote and local computers are the self-same machine, with the implication that rule engine resolution order should be the same remotely as it is locally.

scenario (1): 
------
With the irods rule language plugin preceding the python rule language in the server config's resolution order, and a rule file `py_re_testexec.r` containing:

```
def danRule(rule_args, callback, rei):
  callback.delayExec ("<PLUSET>1s</PLUSET>", "writeLine('serverLog','delaytest')","")
  callback.remoteExec ("daniel-ThinkPad-W540","","writeLine('serverLog','remotetest')","")

INPUT null
OUTPUT ruleExecOut
```

and executed via `irule  -r irods_rule_engine_plugin-python-instance -F py_re_testexec.r` , we arrive at this (expected) output in the serverLog:

```
May  4 15:50:45 pid:495 NOTICE: writeLine: inString = remotetest
May  4 15:51:13 pid:502 NOTICE: writeLine: inString = delaytest
```

scenario (2):
------
Reversing the order of resolution then -- so that the  python rule engine plugin comes first and irods rule language second -- and this time using a rule file  `py_py_testexec.r` containing the following (note  the `callback` object is referred to in the rule code because the python rule plugin will be answering):

```
def danRule(rule_args, callback, rei):
 callback.delayExec ("<PLUSET>1s</PLUSET>", "callback.writeLine('serverLog','delaytest')","")
 callback.remoteExec ("daniel-ThinkPad-W540","","callback.writeLine('serverLog','remotetest')","")

INPUT null
OUTPUT ruleExecOut
```

After this time invoking via `irule  -r irods_rule_engine_plugin-python-instance -F py_py_testexec.r` we see the following in the  server log (after waiting for the output from the delayExec to appear):

```
May  4 15:52:46 pid:584 remote addresses: 127.0.0.1, 152.54.9.29 ERROR: [exec_rule_text:532] Improperly formatted rule text in Python rule engine plugin
May  4 15:52:46 pid:584 remote addresses: 127.0.0.1, 152.54.9.29 ERROR: rsExecMyRule : -1828000, [-]	/tmp/tmpC8lQD0/irods_rule_engine_plugin-python.cxx:533:irods::error exec_rule_text(const irods::default_re_ctx &, const std::string &, msParamArray_t *, const std::string &, irods::callback) :  status [RULE_ENGINE_ERROR]  errno [] -- message [Improperly formatted rule_text]

May  4 15:52:46 pid:584 DEBUG: 
May  4 15:52:46 pid:584 remote addresses: 127.0.0.1, 152.54.9.29 ERROR: caught python exception: Traceback (most recent call last):
  File "<string>", line 12, in danRule
RuntimeError: [iRods__Error__Code:-1828000] [-]	/tmp/tmpLGq9_F/server/re/include/irods_re_plugin.hpp:321:irods::error irods::dynamic_operation_execution_manager<std::__1::tuple<>, RuleExecInfo *, irods::rule_execution_manager_pack::DONT_AUDIT_RULE>::call(std::string, std::string, OP, As &&...) [T = std::__1::tuple<>, C = RuleExecInfo *, Audit = irods::rule_execution_manager_pack::DONT_AUDIT_RULE, OP = std::__1::function<irods::error (const std::__1::basic_string<char> &, irods::re_pack_inp<std::__1::tuple<> > &, irods::unpack &&)>, As = <const std::__1::basic_string<char> &, irods::re_pack_inp<std::__1::tuple<> > &, irods::unpack>] :  status [RULE_ENGINE_ERROR]  errno [] -- message [applyRuleUpdateParams failed for rule remoteExec]
	[-]	/tmp/tmpLGq9_F/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/libirods_rule_engine_plugin-irods_rule_language.cpp:348:irods::error exec_rule(irods::default_re_ctx &, const std::string &, std::list<boost::any> &, irods::callback) :  status [RULE_ENGINE_ERROR]  errno [] -- message [applyRuleUpdateParams failed for rule remoteExec]


May  4 15:52:46 pid:584 remote addresses: 127.0.0.1, 152.54.9.29 ERROR: rsExecMyRule : -1828000, [-]	/tmp/tmpC8lQD0/irods_rule_engine_plugin-python.cxx:539:irods::error exec_rule_text(const irods::default_re_ctx &, const std::string &, msParamArray_t *, const std::string &, irods::callback) :  status [RULE_ENGINE_ERROR]  errno [] -- message [irods_rule_engine_plugin_python::irods::error exec_rule_text(const irods::default_re_ctx &, const std::string &, msParamArray_t *, const std::string &, irods::callback) Caught Python exception.
Traceback (most recent call last):
  File "<string>", line 12, in danRule
RuntimeError: [iRods__Error__Code:-1828000] [-]	/tmp/tmpLGq9_F/server/re/include/irods_re_plugin.hpp:321:irods::error irods::dynamic_operation_execution_manager<std::__1::tuple<>, RuleExecInfo *, irods::rule_execution_manager_pack::DONT_AUDIT_RULE>::call(std::string, std::string, OP, As &&...) [T = std::__1::tuple<>, C = RuleExecInfo *, Audit = irods::rule_execution_manager_pack::DONT_AUDIT_RULE, OP = std::__1::function<irods::error (const std::__1::basic_string<char> &, irods::re_pack_inp<std::__1::tuple<> > &, irods::unpack &&)>, As = <const std::__1::basic_string<char> &, irods::re_pack_inp<std::__1::tuple<> > &, irods::unpack>] :  status [RULE_ENGINE_ERROR]  errno [] -- message [applyRuleUpdateParams failed for rule remoteExec]
	[-]	/tmp/tmpLGq9_F/plugins/rule_engines/irods_rule_engine_plugin-irods_rule_language/libirods_rule_engine_plugin-irods_rule_language.cpp:348:irods::error exec_rule(irods::default_re_ctx &, const std::string &, std::list<boost::any> &, irods::callback) :  status [RULE_ENGINE_ERROR]  errno [] -- message [applyRuleUpdateParams failed for rule remoteExec]


]

May  4 15:53:14 pid:590 NOTICE: writeLine: inString = delaytest
```

This shows that although the python rule engine is "picking up the phone" for scenario (2) -- as one would predict -- the existence of the callback object, while recognized during the evaluation of the delayExec() call, is *NOT* recognized  during the remoteExec() call.

**Comment by d-w-moore** [comment]
Also quite incidentally, the use of `-r` switch is optional in the invocation of `irule` for scenario (2), due to the python rule engine getting "first shot" here.  I did, however, verify the results were the same both ways.
